# -*- coding: utf-8 -*-
"""Module_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUNBRS5MBCk6kdjSKHk-0ZHgaubWu-5T
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

customer_df = pd.read_csv("Revenue_Cat_Customer_Export.csv", sep=";")
expired_df = pd.read_csv("expired.csv", sep=";")

combined_data = pd.concat([customer_df, expired_df], ignore_index=True)
combined_data = combined_data[[
    "first_seen_at", "last_seen_at",
    "first_purchase_at", "trial_start_at", "trial_end_at",
    "most_recent_renewal_at", "latest_expiration_at",
    "subscription_opt_out_at",
    "status", "total_renewals", "total_spent"
]].copy()

combined_data = combined_data.dropna(axis=1, how="all")

#transforming date cols for data validation
date_cols = [
    "first_purchase_at", "trial_start_at", "trial_end_at",
    "most_recent_renewal_at", "subscription_opt_out_at",
    "latest_expiration_at", "last_seen_at", "first_seen_at"
]

for col in date_cols:
    if col in combined_data.columns:
        combined_data[col] = pd.to_datetime(combined_data[col], unit='ms', errors='coerce')

# encoding non-numeric values
cols_to_encode = ['status']
encoders = {}

for col in cols_to_encode:
    le = LabelEncoder()
    combined_data[col] = le.fit_transform(combined_data[col].astype(str))
    encoders[col] = le

#forming calculations out of date data
# active days
combined_data['active_days'] = (
    combined_data['last_seen_at'] - combined_data['first_purchase_at']
).dt.days

combined_data['active_days'] = combined_data['active_days'].fillna(0)

combined_data.loc[combined_data['active_days'] < 0, 'active_days'] = 0

# trial + conversion
combined_data['had_trial'] = combined_data['trial_start_at'].notna().astype(int)

combined_data['converted'] = (
    (combined_data['had_trial'] == 1) &
    (combined_data['total_renewals'] >= 1)
).astype(int)

# recency
combined_data['days_since_last_seen'] = (
    pd.Timestamp.today() - combined_data['last_seen_at']
).dt.days

combined_data['days_since_last_seen'] = combined_data['days_since_last_seen'].fillna(0)

combined_data.loc[combined_data['days_since_last_seen'] < 0, 'days_since_last_seen'] = 0

# billing issues
billing_issue_code = encoders['status'].transform(['billing_issue'])[0]
billing_issue_trial_code = encoders['status'].transform(['billing_issue_trial'])[0]

combined_data['had_billing_issue'] = combined_data['status'].isin(
    [billing_issue_code, billing_issue_trial_code]
).astype(int)

# opt out
combined_data['opted_out'] = combined_data['subscription_opt_out_at'].notna().astype(int)

#is_active
active_code = encoders['status'].transform(['active'])[0]
combined_data['is_active'] = (combined_data['status'] == active_code).astype(int)

# days since renewal
combined_data['days_since_renewal'] = (
    pd.Timestamp.today() - combined_data['most_recent_renewal_at']
).dt.days

combined_data['days_since_renewal'] = combined_data['days_since_renewal'].fillna(0)
combined_data.loc[combined_data['is_active'] == 1, 'days_since_renewal'] = -1

combined_data.loc[combined_data['days_since_renewal'] < 0, 'days_since_renewal'] = 0
combined_data.loc[combined_data['is_active'] == 1, 'days_since_renewal'] = -1

# expiration gap
combined_data['expired_gap'] = (
    combined_data['last_seen_at'] - combined_data['latest_expiration_at']
).dt.days

combined_data['expired_gap'] = combined_data['expired_gap'].fillna(0)
combined_data.loc[combined_data['expired_gap'] < 0, 'expired_gap'] = 0

combined_data.head()

"""Final dataframe and k-means analysis:"""

features = combined_data[[
    "total_spent",
    "total_renewals",
    "active_days",
    "days_since_last_seen",
    "days_since_renewal",
    "had_trial",
    "converted",
    "had_billing_issue",
    "opted_out",
    "expired_gap",
    "is_active"
]].copy()

#clean and scale so values do not overpower one another
features = features.replace([float('inf'), -float('inf')], 0)
features = features.fillna(0)

scaler = StandardScaler()
data_scaled = scaler.fit_transform(features)

def optimise_k(data, max_k):
    means = []
    inertias = []

    for k in range(1, max_k):
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit(data)
        means.append(k)
        inertias.append(kmeans.inertia_)

    return means, inertias

means_for_plot, inertias_for_plot = optimise_k(data_scaled, 10)

plt.figure(figsize=(10,5))
plt.plot(means_for_plot, inertias_for_plot, 'o-')
plt.xlabel('Number of clusters, k')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

#closer look of the plot, numeric version
optimise_k(data_scaled, 10)

#applying k-means clustering
k = 3
#so that clusters don't change! for graph purposes
cluster_model = KMeans(n_clusters=k, random_state=42, n_init=10)
cluster_model.fit(data_scaled)

combined_data['cluster'] = cluster_model.labels_
cluster_summary = combined_data.groupby("cluster").mean(numeric_only=True)
print(cluster_summary)

print(combined_data["cluster"].value_counts())

# plotting results
pca = PCA(n_components=2)
data_2d = pca.fit_transform(data_scaled)

plt.scatter(
    data_2d[:, 0],
    data_2d[:, 1],
    c=combined_data['cluster'],
    cmap='Set1',
    alpha=0.6
)
plt.title("KMeans Clusters")
plt.show()

for i in range(3):  # since k = 3
    print(f"\nCluster{i}")
    print(combined_data[combined_data['cluster'] == i][features.columns].sample(3))