# -*- coding: utf-8 -*-
"""module6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0DncFT1-Al4u2QEac8xtLp6dYsjnbtk
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from IPython.display import display

# loading data
df = pd.read_csv("dataset.csv")

print("Shape:", df.shape)
print(df.head(10))

# clean data
df = df.drop_duplicates()
df = df.dropna()

df["explicit"] = df["explicit"].astype(int)
df["duration_minutes"] = df["duration_ms"] / 60000

#labels
# 1 = popular song, 0 = not popular
df["popular_song"] = (df["popularity"] >= 50).astype(int)

print("\nClass distribution:")
print(df["popular_song"].value_counts())

#features
features = ["duration_minutes","explicit","danceability","energy","loudness","speechiness",
            "acousticness","instrumentalness","liveness","valence","tempo"]

X = df[features]
y = df["popular_song"]

#training
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y)

#training decision tree
model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

# eval
preds = model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, preds))

print("\nClassification Report:")
print(classification_report(y_test, preds))

#feature importance
importance = pd.Series(model.feature_importances_, index=features).sort_values(ascending=False)

plt.figure(figsize=(8, 5))
importance.plot(kind="bar")
plt.title("Feature Importance")
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

print("\nFeature Importance:")
print(importance)

#wrong predictions
results = df.loc[X_test.index].copy()
results["actual"] = y_test.values
results["predicted"] = preds

wrong = results[results["actual"] != results["predicted"]].head(5)


display(
    wrong[["track_name","artists","track_genre","popularity","actual","predicted"] + features]
)

#confusion matrix
cm = confusion_matrix(y_test, preds)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion Matrix")
plt.show()
